api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "pos-action"
uid = "8a3d8821-4959-69ee-f3d9-ef8c2abbdabbdfa70b63"
handle = "pos-action"
description = "Gift Card Options"

# module: path to the file that contains your extensionâ€™s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Action.jsx"
target = "pos.cart.line-item-details.action.render"

# You can omit the menu-item target and POS will provide a default menu item for this extension.
# The menu item will present the action target on click.
# This template has the same behavior as the POS-provided default, but is included for completeness.
[[extensions.targeting]]
module = "./src/MenuItem.jsx"
target = "pos.cart.line-item-details.action.menu-item.render"
